name: magicexpansion
## CHANGE this to your username.
author: Yomicer
version: ${project.version}
main: io.Yomicer.magicExpansion.MagicExpansion
api-version: '1.20'
depend: [Slimefun]
softdepend:
  - RykenSlimeCustomizer
## CHANGE this to a meaninful but short description of your plugin.
description: Have fun

commands:
  magicexpansion:
    description: MagicExpansion 插件主指令
    usage: /magicexpansion <reload slimefun>
    permission: magicexpansion.command
    permission-message: &c你没有权限执行此指令！

  mxw:
    description: Main command for map management.

  mxf:
    description: 钓鱼图鉴相关命令
    usage: /<command> <open_guide|guide>


  mxai:
    description: AI聊天控制
    usage: /mxai <chaton|chatoff|public|publicmode>
    permission: mxai.use
    permission-message: 你没有使用AI命令的权限！

#  record:
#    description: 开始或停止录制玩家行为
#    usage: /<command> start|stop
#    permission: magicexpansion.record
#
#  playback:
#    description: 回放之前录制的行为
#    usage: /<command> [stop]
#    permission: magicexpansion.playback

  mxwand:
    description: 魔法祭坛相关命令
    usage: /<command> wand
    permission: mxwand.wand

  mxalter:
    description: 获取配方书命令
    usage: /<command> <guide|open_guide>


permissions:
  MagicExpansionMachines.use:
    description: Allows players to use the plugin commands.
    default: op

  mxai.use:
    description: 可以使用AI聊天功能
    default: true
  mxai.op:
    description: 可以控制全服AI模式开关
    default: op  # 只有OP或有此权限的玩家可用

  mxwand.wand:
    description: 获取魔法祭坛魔杖
    default: op


#  magicexpansion.record:
#    description: 可以使用 /record 命令
#    default: op
#
#  magicexpansion.playback:
#    description: 可以使用 /playback 命令
#    default: op
