name: magicexpansion
## CHANGE this to your username.
author: Yomicer
version: ${project.version}
main: io.Yomicer.magicExpansion.MagicExpansion
api-version: '1.20'
depend: [Slimefun]
softdepend:
  - RykenSlimeCustomizer
## CHANGE this to a meaninful but short description of your plugin.
description: Have fun

commands:
  magicexpansion:
    description: MagicExpansion 插件主指令
    usage: /magicexpansion <reload slimefun>
    permission: magicexpansion.command
    permission-message: &c你没有权限执行此指令！

  mx:
    description: Main command for map management.
  permissions:
    MagicExpansionMachines.use:
      description: Allows players to use the plugin commands.
      default: op